CREATE OR REPLACE PROCEDURE "DBO"."INSERT_RECORD_RANJAN_ROUT"("CUSTOMERID_PARAM" VARCHAR(16777216), "HOTELBRANCHNO_PARAM" VARCHAR(16777216), "BOOKINGDATE_PARAM" DATE, "PAYMENTMETHOD_PARAM" VARCHAR(16777216), "CUSTOMERTYPE_PARAM" VARCHAR(16777216), "ROOMCATEGORY_PARAM" VARCHAR(16777216), "TRANSACTIONYEARMONTH_PARAM" VARCHAR(16777216), "CLOSINGDATE_PARAM" VARCHAR(16777216), "TOTALINVOICEAMOUNTINUSD_PARAM" NUMBER(38,0), "INVOICEQUANTITY_PARAM" NUMBER(38,0), "COUNTRYNAME_PARAM" VARCHAR(16777216), "COUNTRYCODE_PARAM" VARCHAR(16777216), "STARTDATE_PARAM" DATE, "ENDDATE_PARAM" DATE, "SALARY_PARAM" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
    BEGIN
        INSERT INTO RANJAN_TABLE_4 (
            CUSTOMERID, 
            HOTELBRANCHNO, 
            BOOKINGDATE, 
            PAYMENTMETHOD, 
            CUSTOMERTYPE, 
            ROOMCATEGORY, 
            TRANSACTIONYEARMONTH, 
            CLOSINGDATE, 
            TOTALINVOICEAMOUNTINUSD, 
            INVOICEQUANTITY, 
            COUNTRYNAME, 
            COUNTRYCODE, 
            STARTDATE, 
            ENDDATE, 
            SALARY
        ) VALUES (
            CUSTOMERID_PARAM, 
            HOTELBRANCHNO_PARAM, 
            BOOKINGDATE_PARAM, 
            PAYMENTMETHOD_PARAM, 
            CUSTOMERTYPE_PARAM, 
            ROOMCATEGORY_PARAM, 
            TRANSACTIONYEARMONTH_PARAM, 
            CLOSINGDATE_PARAM, 
            TOTALINVOICEAMOUNTINUSD_PARAM, 
            INVOICEQUANTITY_PARAM, 
            COUNTRYNAME_PARAM, 
            COUNTRYCODE_PARAM, 
            STARTDATE_PARAM, 
            ENDDATE_PARAM, 
            SALARY_PARAM
        );

        RETURN "Record inserted successfully";
    END;
';
-----------------------------------------------------------------------------
