create or replace TABLE DBO."CUSTOMER_Test" (
	FIRSTNAME VARCHAR(20),
	MIDDLENAME VARCHAR(20),
	LASTNAME VARCHAR(20),
	CUSTOMERNAME VARCHAR(80),
	ADDRESS VARCHAR(100),
	CITY VARCHAR(50),
	PHONE NUMBER(10,0),
	EMAIL VARCHAR(50),
	SSN VARCHAR(20),
	GENDER VARCHAR(6),
	AGE NUMBER(10,0),
	CUSTOMERID VARCHAR(50),
	STATE VARCHAR(100)
);