create or replace TRANSIENT TABLE "DBO"."AB_Demo_TEST_trn" (
	"Name" VARCHAR(50) NOT NULL,
	"Emp_ID" NUMBER(38,0) NOT NULL,
	"Gender" VARCHAR(50),
	SALARY NUMBER(38,0),
	DOB DATE NOT NULL,
	ADDRESS VARCHAR(50)
);