CREATE OR REPLACE FUNCTION "DBO"."GETPOSITION_RANJAN_7"("P_EMPLOYEEID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS '
    SELECT Position
    FROM Employees_RANJAN_ROUT_7
    WHERE EmployeeID = p_EmployeeID
   -- FETCH FIRST ROW ONLY;
';