create or replace TABLE "DBO"."AB_Demo_TEST" (
	"Name" VARCHAR(50),
	"Emp_ID" NUMBER(38,0),
	"Gender" VARCHAR(50),
	SALARY NUMBER(38,0),
	DOB DATE NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	"col1" FLOAT,
	COL2 BINARY(8388608)
);