create or replace TABLE "DBO".DATATYPE (
	AA1 VARCHAR(20) DEFAULT '10avf',
	BB1 BINARY(10),
	CC22 NUMBER(38,0) DEFAULT 123,
	DD1 DATE,
	F1 FLOAT DEFAULT 1010,
	E1 BOOLEAN DEFAULT TRUE,
	G1 GEOMETRY DEFAULT 'Point(34)',
	GFRT1 ARRAY DEFAULT ARRAY_CONSTRUCT(1, 2, 3),
	ASE34 OBJECT DEFAULT OBJECT_CONSTRUCT('Alberta', 'Edmonton'),
	V VARIANT DEFAULT PARSE_JSON('1.23')
);