create or replace TABLE "DBO".EMP1 (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	EMPLOYEE_NAME VARCHAR(200),
	DEPARTMENT_ID NUMBER(38,0),
	SALARY NUMBER(10,7),
	primary key (EMPLOYEE_ID),
	foreign key (DEPARTMENT_ID) references DBO.DEPARTMENTS(DEPARTMENT_ID)
);