create or replace TABLE "DBO".EMP2 (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	EMPLOYEE_NAME VARCHAR(100),
	DEPARTMENT_ID NUMBER(38,0),
	SALARY NUMBER(10,2),
	primary key (EMPLOYEE_ID),
	foreign key (DEPARTMENT_ID) references DBO.DEPARTMENTS(DEPARTMENT_ID)
);