create or replace TABLE "DBO".EMPLOYEE_BASICINFO (
	EMP_ID NUMBER(38,0) NOT NULL,
	AGE NUMBER(38,0),
	GENDER VARCHAR(50),
	EDUCATION VARCHAR(50),
	JOB_TITLE VARCHAR(50),
	JOINING_DATE DATE,
	YEARS_OF_EXPERIENCE FLOAT,
	SALARY NUMBER(38,0),
	MONTH NUMBER(38,0),
	YEAR NUMBER(38,0),
	QUARTER NUMBER(38,0),
	JOININGMONTH NUMBER(38,0),
	JOINING_MONTH VARCHAR(50),
	JOININGQUARTER NUMBER(38,0),
	JOINING_QUARTER VARCHAR(50),
	EMPLOYEE_RATINGS NUMBER(9,4)
);