create or replace TABLE "DBO".EMPLOYEE_BASICDETAILS (
	EMP_ID NUMBER(38,0) NOT NULL,
	AGE NUMBER(38,0),
	GENDER VARCHAR(50),
	EDUCATION VARCHAR(50),
	JOB_TITLE VARCHAR(50),
	JOINING_DATE DATE,
	YEARS_OF_EXPERIENCE FLOAT,
	SALARY NUMBER(38,0)
);