create or replace TABLE "DBO".EMPLOYEE_DETAILS (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(50),
	AGE NUMBER(38,0),
	CURRENT_ADDRESS VARCHAR(50),
	EMAIL VARCHAR(50),
	BUSINESS VARCHAR(50),
	PHONE NUMBER(38,0),
	JOINING_DATE DATE,
	SALARY NUMBER(38,0)
);