create or replace TABLE "DBO".EMPLOYEE_DATA_SQL (
	EMPLOYEE_ID NUMBER(38,0),
	NAME VARCHAR(100),
	DESIGNATION VARCHAR(100),
	CONTACT_NUMBER NUMBER(38,0),
	EMAIL VARCHAR(100),
	EMP_ADDRESS VARCHAR(100),
	DEPT_ID NUMBER(38,0),
	DEPT_NAME VARCHAR(100),
	SALARY NUMBER(38,0),
	constraint EMPLOYEE_ID primary key (EMPLOYEE_ID)
);