create or replace TABLE "DBO".EMPLOYEE_DETAILS_1 (
	ID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(15),
	ADDRESS VARCHAR(50),
	STARTDATE VARCHAR(15),
	ENDDATE DATE,
	ZIPCODE VARCHAR(50),
	SALARY NUMBER(18,0),
	ADDRESS02 VARCHAR(50),
	TESTBLANK VARCHAR(10),
	COLUMN_A VARCHAR(1000)
);