create or replace TABLE "DBO".EMPLOYEE_DETAILS_2 (
	ID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(15),
	ADDRESS VARCHAR(50),
	STARTDATE VARCHAR(15),
	ENDDATE DATE,
	ZIPCODE VARCHAR(50),
	ADDRESS02 VARCHAR(50),
	COLUMN_A VARCHAR(1000),
	SALARY VARCHAR(50),
	EXTERNALACQCOST100 NUMBER(38,0),
	EXTERNALACQUISITIONCOSTMULTIPLIER NUMBER(38,0),
	SECTIONREFERENCE VARCHAR(50)
);