create or replace TABLE "DBO".ENTITYRULESNOWFLAKE (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(50),
	ADDRESS VARCHAR(50),
	SALARY NUMBER(38,0),
	DEPARTMENT VARCHAR(50),
	CREATEDBY NUMBER(38,0),
	CREATEDON VARCHAR(50),
	PIN_CODE NUMBER(38,0),
	MAIL VARCHAR(50),
	ADDRESS1 VARCHAR(50),
	CREATE_DATE DATE
);