create or replace TABLE "DBO".FLIGHT (
	FLIGHTID NUMBER(38,0),
	FLIGHTNUMBER VARCHAR(10),
	DEPARTUREDATE DATE,
	DEPARTURECITY VARCHAR(50),
	DESTINATIONCITY VARCHAR(50),
	SEATNO NUMBER(38,0),
	constraint PK primary key (FLIGHTID)
);