create or replace TABLE "DBO".FLIGHT (
	FLIGHTID NUMBER(38,0) NOT NULL,
	FLIGHTNUMBER VARCHAR(10),
	DEPARTUREDATE DATE,
	DEPARTURECITY VARCHAR(16777216) NOT NULL,
	DESTINATIONCITY VARCHAR(50),
	primary key (FLIGHTID),
	constraint UQ_FLIGHTNUMBER unique (FLIGHTNUMBER)
);