create or replace TABLE "DBO"."flight1" (
	FLIGHTID NUMBER(38,0),
	ID NUMBER(38,0) NOT NULL,
	FLIGHTNUMBER VARCHAR(10),
	DEPARTUREDATE DATE,
	DEPARTURECITY VARCHAR(50),
	DESTINATIONCITY VARCHAR(50),
	constraint PK primary key (FLIGHTID, ID)
);