create or replace TABLE "DBO".FRNGKEY (
	EXCHANGERATETYPE VARCHAR(10) NOT NULL,
	FROMCURRENCY VARCHAR(10) NOT NULL,
	TOCURRENCY VARCHAR(10) NOT NULL,
	VALIDFROM DATE NOT NULL,
	EXCHANGERATE NUMBER(17,7) NOT NULL,
	RATIOFROM NUMBER(17,3),
	RATIOTO NUMBER(17,3),
	"exCHANGERATETYPe1" NUMBER(17,3) NOT NULL,
	primary key ("exCHANGERATETYPe1")
);