create or replace TABLE "DBO".LARGE_DATA_1_SF (
	CUSTOMERID VARCHAR(50),
	HOTELBRANCHNO VARCHAR(50),
	BOOKINGDATE DATE,
	PAYMENTMETHOD VARCHAR(50),
	CUSTOMERTYPE VARCHAR(50),
	ROOMCATEGORY VARCHAR(50),
	TRANSACTIONYEARMONTH VARCHAR(50),
	CLOSINGDATE VARCHAR(50),
	TOTALINVOICEAMOUNTINUSD NUMBER(37,0),
	INVOICEQUANTITY NUMBER(37,0)
);