create or replace TABLE "DBO".MOCK_DATA (
	EMPLOYEE_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	AGE NUMBER(38,0),
	EMAIL VARCHAR(200),
	GENDER VARCHAR(200),
	JOB_TITLE VARCHAR(200),
	DEPARTMENT VARCHAR(200),
	HIRE_DATE DATE,
	SALARY NUMBER(9,4)
);