create or replace TABLE "DBO".PURCHASE_ORDER123 (
	INVOICEID FLOAT,
	INVOICETYPE VARCHAR(50),
	PURCHASEORDER2 VARCHAR(50),
	ORDERTYPE VARCHAR(50),
	FINALPRODUCTTYPE VARCHAR(50),
	CUSTOMERSPECIFICID VARCHAR(50)
);