create or replace TABLE "DBO".S_EMPLOYEEDETAILS_TEST (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(50),
	AGE NUMBER(38,0),
	CURRENT_ADDRESS VARCHAR(50),
	EMAIL VARCHAR(100),
	BUSINESS VARCHAR(50),
	PHONE NUMBER(38,0),
	JOINING_DATE DATE,
	SALARY NUMBER(38,0),
	DEPT_ID NUMBER(38,0),
	"dept_name" VARCHAR(50),
	constraint PK primary key ("dept_name")
);