create or replace TABLE "DBO".SALESTRANSACTIONS (
	CUSTOMERID VARCHAR(100),
	PRODUCTNUM VARCHAR(100),
	FACTDATE DATE,
	SALESQTY NUMBER(38,0),
	SALESUOM VARCHAR(100),
	PLANTYPE VARCHAR(100),
	TRANSACTIONTYPE VARCHAR(100),
	CUSTOMERACCOUNTID NUMBER(38,0)
);