create or replace TABLE "DBO".SALESDETAILS (
	CUSTOMERID VARCHAR(100),
	PRODUCTNUM VARCHAR(100),
	FACTDATE DATE,
	SALESUOM VARCHAR(100),
	PLANTYPE VARCHAR(100),
	TRANSACTIONTYPE VARCHAR(100),
	CUSTOMERACCOUNTID NUMBER(38,0),
	SALESQTY NUMBER(38,0),
	SALESAMOUNTINUSD NUMBER(38,0)
);