create or replace TRANSIENT TABLE "TRANSIENT".SMALLDATATEST (
	ID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	"DimLocation" VARCHAR(15),
	"CountryCode" VARCHAR(50),
	STARTDATE VARCHAR(15),
	ENDDATE DATE,
	ADDRESS VARCHAR(50)
);